Ot101 71 Crear migración y modelo Contactos
alkemyTech/OT101-Server pull request #20
Opened 2021-12-02 16:25 UTC by alejandropascuale

2021-12-02 23:28 UTC, Nico-14 requested changes
### Quedaron estos archivos de otra tarea o pruebas:
- app.js
- controllers/backofficeController.js 
- controllers/mainController.js
- routes/.DB_Store
- routes/backoffice.js
- routes/index.js

2021-12-03 20:19 UTC, Nico-14 approved these changes

2021-12-04 04:32 UTC, germansanz93 approved these changes
Ale el codigo lo veo de diez, lo unico que tenes dos archivos .DS_Store. Creo que te los crea solo Mac OS. Habria que sacarlos del repo

2021-12-08 18:55 UTC, hfoncea approved these changes

2021-12-08 18:55 UTC, merged