Ot101 33 logica jwt
alkemyTech/OT101-Server pull request #22
Opened 2021-12-03 18:13 UTC by germansanz93

Tuve que hacer un refactor de las rutas de user para sacar la logica de los controllers fuera del router y poder trabajar de forma mas organizada.

Cree authConfig.js que tiene las configuraciones relacionadas al token

En el metodo login del authController esta la creacion y envio del token (el metodo enviaba ademas el usuario, no lo quise tocar, solo agregue el token)

En middlewares cree authJWT que tiene el metodo verifyToken el cual sirve para poner de middleware en las rutas en las que se deba verificar si hay una sesion.

verifyToken si no recibe token
![Screenshot from 2021-12-03 12-12-46](https://user-images.githubusercontent.com/64764636/144651893-766548a9-2d71-4a33-ac1b-ca8b8341b306.png)

verifyToken si el token no es valido
![Screenshot from 2021-12-03 12-18-06](https://user-images.githubusercontent.com/64764636/144651947-57824783-47d8-4a9f-91f6-b8bf35201a88.png)

VerifyToken si el token se verifica correctamente
![Screenshot from 2021-12-03 12-29-32](https://user-images.githubusercontent.com/64764636/144652024-607b4f44-9a52-478d-9b85-e687b12b7339.png)

Creacion del token en el login y envio en el response
![Screenshot from 2021-12-03 14-56-00](https://user-images.githubusercontent.com/64764636/144652121-8f363d15-c0c1-46b1-b991-e1620766a0a8.png)

2021-12-03 20:27 UTC, Nico-14 commented on middlewares/authJWT.js
> +      req.userId = decoded.id;
Cambiar el req.userId por req.user.id para que funcione el middleware **isAdmin**. O hacer los cambios en el middleware **isAdmin**

2021-12-03 20:32 UTC, Nico-14 requested changes

2021-12-03 20:32 UTC, Nico-14 commented on middlewares/isAdmin.js
> +    const user = await User.findOne({ where: { id: req.user.id }, include: { model: Role, as: 'role' } });
Acá hice que el id del usuario se obtenga desde **req.user.id**, debería quedar igual que en el **verifyToken**: **req.userId**, o cambiarlo en el **verifyToken (middlewares/authJWT.js, linea: 20)**

2021-12-03 21:18 UTC, germansanz93 commented on middlewares/isAdmin.js
> +    const user = await User.findOne({ where: { id: req.user.id }, include: { model: Role, as: 'role' } });
No te hagas drama, ahi mergeo con lo que esta y hago de nuevo el PR

2021-12-04 23:18 UTC, mateo-14 approved these changes

2021-12-08 18:52 UTC, merged