Ot101 53 listar usuarios
alkemyTech/OT101-Server pull request #31
Opened 2021-12-04 23:02 UTC by FranciscoMessina

Completed endpoint to list users, if you are an admin.

2021-12-05 03:13 UTC, germansanz93 approved these changes
Francisco, no le veo nada malo al codigo.. Lo que si acordate que dijo hugo que no subamos el package-lock.

2021-12-06 23:25 UTC, FranciscoMessina commented
Si, tenes razón se me paso en los 3 que hice .

2021-12-08 19:43 UTC, FranciscoMessina commented
Arreglo los conflictos.

2021-12-10 13:53 UTC, pabloameni requested changes
Bien Fran, salvo algunos cambios hechos a código ajeno a la incidencia.

2021-12-10 13:53 UTC, pabloameni commented on controllers/newsController.js
> +      attributes: ['name', 'image'],
En la incidencia OT101-11 dice que: _Devolverá solamente los campos name, image y createdAt_ Entonces si te daba error esta línea debería corregirse el modelo / migration / seeder.

2021-12-10 13:53 UTC, pabloameni commented on routes/news.js
> +router.post('/', newsValidation, validationHandler, newsController.create);
Tenes una versión vieja del archivo, ahora en develop esa línea dice `router.post('/', s3multerUpload.single('image'), newsValidation, validationHandler, newsController.create);`. Aparte esa línea funcionaba solo que daba error si no encontraba la configuración de S3.

2021-12-10 13:53 UTC, pabloameni commented on controllers/newsController.js
> +      const { name, image, type, categoryId } = req.body
Según código `image` es un string,  estás esperando que te envíen la imagen en base64 o su URL? Quien subiría la imágen al back?

2021-12-11 18:39 UTC, FranciscoMessina commented on controllers/newsController.js
> +      const { name, image, type, categoryId } = req.body
Si, no estoy seguro de como se maneja esto con el tema de S3 y eso.

2021-12-11 18:40 UTC, FranciscoMessina commented on routes/news.js
> +router.post('/', newsValidation, validationHandler, newsController.create);
Si, la habia sacado para probar porque no tenia la config  de S3 y me olvide de agregarla, re colgado.

2021-12-11 18:43 UTC, FranciscoMessina commented on controllers/newsController.js
> +      attributes: ['name', 'image'],
Claro, tiene sentido.

2021-12-12 14:26 UTC, FranciscoMessina reviewed
Hice los cambios solicitados.

2021-12-13 01:54 UTC, pabloameni approved these changes

2021-12-13 01:54 UTC, pabloameni commented on controllers/newsController.js
> +      const { name, image, type, categoryId } = req.body
Simplemente agregas a la ruta, como un middleware luego del path, ` s3multerUpload.single('image')`
Si tenes las credenciales las sube a S3 sino copia el archivo en memoria. Y luego en el controller tendrías la URL de la imagen en `req.file?.location` (si es que enviaron una)

2021-12-15 00:36 UTC, merged