Ot101 89 endpoint listar miembros
alkemyTech/OT101-Server pull request #48
Opened 2021-12-15 11:51 UTC by alejandropascuale

2021-12-15 13:25 UTC, pabloameni requested changes
Bien ale, al endpoint solo le falta el verifyToken. Pero así como no está no compila

2021-12-15 13:25 UTC, pabloameni commented on .gitignore
> +bin/www
Ale, ese archivo contiene código por más que esté en bin/ así que tiene que estar en los cambios de git. Imagino que fue para poder cambiarle el puerto que usa el servidor. Para cambiar el puerto no necesitas modificar el bin/www si no que basta con agregar PORT=xxxx al archivo .env del raiz

2021-12-15 13:25 UTC, pabloameni commented on routes/members.js
> +const isAdmin = require('../middlewares/isAdmin');
Ya estaba en la linea 9

2021-12-15 13:25 UTC, pabloameni commented on routes/members.js
> +router.get('/', isAdmin, membersController.list);
Antes del isAdmin hay que utilizar siempre verifyToken.

2021-12-15 13:25 UTC, pabloameni commented on routes/members.js
> +var router = express.Router();
Es preferible `const` ya que siempre es recomendable utilizar el tipo de datos más estricto posible.

2021-12-15 13:50 UTC, alejandropascuale commented on .gitignore
> +bin/www
Si tal cual, lo paso como variable de entorno y lo saco del gitignore

2021-12-20 14:22 UTC, alejandropascuale commented
@pabloameni ya esta añadido el verifyToken y controlé que compila bien

2021-12-21 10:27 UTC, hfoncea approved these changes

2021-12-21 10:27 UTC, merged